### ISSUE TITLE
加入菜单栏图标

### ISSUE THREAD

**Issue by bestony** [LanceGin/QBox#2]
### 需求描述：
如果希望发展成为图床等功能，希望可以有一个菜单栏中的图标。
### 目前动作：
无菜单栏图标
### 预期动作：
菜单栏中有图标，文件拖动到图标上，会上传到设置的默认的 Bucket 中
### 补充说明：
交互逻辑可以参考 [iPic](https://itunes.apple.com/cn/app/ipic-%E5%9B%BE%E5%BA%8A%E7%A5%9E%E5%99%A8-%E4%BC%97%E5%A4%9A%E5%9B%BE%E7%89%87%E4%B8%8A%E4%BC%A0%E6%96%B9%E5%BC%8F-%E6%94%AF%E6%8C%81-markdown/id1101244278?mt=12)

**Comment by LanceGin** [comment]
谢谢建议，这个很nice 准备加入 TODO

**Comment by LanceGin** [comment]
状态栏图标已在1.3.0版本中添加，相应的功能后续版本提交。
